### ISSUE TITLE
🐟 Define Define

### ISSUE THREAD

**Issue by TodePond** [TodePond/MeanPond#1]
# Spoilers!

Release Date: 32nd January

## Music
- [x] Counting the Points (Original Mix) - Andrew Bayer - Anjunabeats
- [x] Counting the Points (Matt Lange Remix) - Matt Lange - Anjunadeep
- [x] Define Define - Pigen

## Code
- [x] PaintLab
- [x] BerdLab (HTML)
- [x] BerdLab (PowerPoint)
- [x] SandLab
- [x] Tetris (Single-Player)
- [x] Tetris (Multi-Player)
- [x] FishLab
- [x] LabLab
- [x] Non-Fungal Todes

## Storyboard
- [x] Intro
- [x] **Programming Language**
- [x] HTML (Markupping Language)
- [x] PowerPoint
- [x] **Cellular Automata**
- [x] Pink Sand (Agent-Based Model)
- [x] Tetris (Cellular Automaton)
- [x] Tetris: Versus Mode
- [x] **Life + Intelligence**
- [x] Fysh (AI + ALife) (AAI + AALife)
- [x] Me
- [x] **Fractal**
- [x] Fractal (Fractal)
- [x] Fractal
- [x] **Art**
- [x] Music (Annoying The Neighbours)
- [x] NFTs
- [x] **Define**
- [x] Tool (Annoying The Neighbours)
- [x] Outro
- [x] Credits
- [x] Patrons

## Script
- [x] Intro
- [x] Programming Language
- [x] Cellular Automata
- [x] Cellular Automata 2
- [x] Life + Intelligence
- [x] Life + Intelligence 2
- [x] Fractal
- [x] Fractal 2
- [x] Art
- [x] Art 2
- [x] Define
- [x] Credits
- [x] Patrons

## Voice
- [x] Intro
- [x] Programming Language
- [x] Cellular Automata
- [x] Cellular Automata 2
- [x] Life + Intelligence
- [x] Life + Intelligence 2
- [x] Fractal
- [x] Fractal 2
- [x] Art
- [x] Art 2
- [x] Define
- [x] Define 2
- [x] Credits
- [x] Patrons

## Video
- [x] Intro
- [x] Programming Language
- [x] Cellular Automata
- [x] Cellular Automata 2
- [x] Life + Intelligence
- [x] Life + Intelligence 2
- [x] Fractal
- [x] Fractal 2
- [x] Art
- [x] Art 2
- [x] Define
- [x] Credits
- [x] Patrons

## Promotion
- [x] Teaser 1
- [x] Teaser 2
- [x] Reviews
- [x] Trailers
- [x] Spoilers
- [ ] Ribbit Report

**Comment by i-rember** [comment]
🤔

**Comment by TodePond** [comment]
Counting the Points -original mix
then Counting the Points - matt lange remix
then No Silence

(with some others thrown in if need)

?

**Comment by TodePond** [comment]
Ok I've laid out some initial todo-lists to get started

**Comment by TodePond** [comment]
Storyboard all done and music mostly done
I reordered fractal + life/intelligence

**Comment by TodePond** [comment]
I shortened/lengthened some sections

**Comment by TodePond** [comment]
berdlabs html done

**Comment by TodePond** [comment]
I should remake berdlab so that it shows a victory screen!

Gonna have a go at paintlab first

**Comment by TodePond** [comment]
done PaintLab

**Comment by TodePond** [comment]
Ok I redid BerdLab (HTML) so that it now shows a victory screen!!

**Comment by TodePond** [comment]
I've started the PPT version of BerdLab

**Comment by TodePond** [comment]
Started some work on SandLab

and added a release date

**Comment by TodePond** [comment]
Made lots of progress on SandLab

gonna change everything to fish

Also I got delayed by covid so I'm pushing back the release date

**Comment by TodePond** [comment]
SandLab coming along more. Gonna try to get a teaser trailer ready now

**Comment by TodePond** [comment]
Teaser trailer was done and released. Intro completely done now. I've started on programming language - gonna make the first transition as a practice + to figure it out.

**Comment by TodePond** [comment]
Audio of intro is dodgy - redo effects

Did more work on sandlab - ready for element making now

**Comment by TodePond** [comment]
First draft of programming language done - still needs lots of review though

- [x] Lowpass drop needs to last longer, and more signposting
- [x] Sort out noise - raise clip volumes and move denoiser to clips
- [x] Make code clips slightly scaled down with void border
- [x] 'my computer' section looks low prod value - zoom into youtube video?
- [x] too many continuity errors with bot-to-bot
- [x] 'going up through HTML' clip is janky
- [x] can't hear myself in correction section

**Comment by TodePond** [comment]
- [x] idea: big bold fancy HTML and CSS and MICROSOFT POWERPOINT! Helps break stuff up, and has now prod value and impact.

- [x] In interruption, change the clips to a one-take. They should stack up over and on top of each other.

- [x] Clouds - remove fade to black, just go straight to black at the start

**Comment by TodePond** [comment]
- [x] Also add slight delay, with me looking at the screen (?), at start of interruption

**Comment by TodePond** [comment]
Ok redid the first part, programming language completely done now

**Comment by TodePond** [comment]
Voice for CA 1 done
Script for CA 2 done

**Comment by TodePond** [comment]
Voice for CA 2 done

**Comment by TodePond** [comment]
Started the video of CA 2 - I think I might switch back to code for CA again!

**Comment by TodePond** [comment]
Did some more sandlab work, and found this:

- [x] Into clouds transition mismatched - the right edge doesnt connect
- [x] Remove mouth noises in intro
- [x] Remove mouth noises in cloud bit
- [x] Consider pushing the CA intro voiceover a tiny bit later, or re-record to get it shorter (and later)? or just keep it crazy?

**Comment by i-rember** [comment]
It's okay, everyone makes mistakes.

**Comment by Magnogen** [comment]
MAKE IT CRAZY

**Comment by TodePond** [comment]
Ok will do!

LabLab code done

**Comment by TodePond** [comment]
Intro noises removed
Clouds fixed

**Comment by TodePond** [comment]
Removed noises from cloud section

**Comment by TodePond** [comment]
Spaced out CA intro a bit but kept it crazy

**Comment by TodePond** [comment]
Gonna give credits a go now

**Comment by TodePond** [comment]
Credits done (except patrons)

**Comment by TodePond** [comment]
- [x] Outro crops wrong
- [x] Outro needs more lead-in

**Comment by TodePond** [comment]
- [x] precision error on cloud entry transition
- [x] pulse cells + rules
- [x] extend patron, delay outro

**Comment by TodePond** [comment]
Outro finished, and credits broll changed, and final highpass transition tuned down a bit

**Comment by TodePond** [comment]
All points fixed. I think I need to press on in chronological order now. Let's finish up sandlab!

**Comment by TodePond** [comment]
SandLab code all done - next up, sandlab video

**Comment by TodePond** [comment]
CA 1 done now

Now facing some options moving forward:
I now know the scope of each section so it would be quicker to do all of each part's job together.

We could batch together: 
- [x] Script
- [x] Transitions
- [x] Voice 1
- [x] Voice 2

I think it would be good to do those next, because then I can just stay in editing mode until the very end

Let's do all of voice 1 first!? but wait, for that... I probably need fishlab code done first...
Is it fishlab time!?

**Comment by TodePond** [comment]
Fish code nearly done

- [x] Allow negative weights
- [x] Consider merging some neurons related to vision/turning?

**Comment by TodePond** [comment]
Ok screw that, FishLab is good enough!

Time to finish the script

**Comment by TodePond** [comment]
Life/Intelligence script 1 done

**Comment by i-rember** [comment]
We're around ⅔ the way there. Good job so far. 👍

**Comment by TodePond** [comment]
Patron pond of fame done. I'll leave it for a day or two in case there are any changes. Back to script!

**Comment by TodePond** [comment]
AI/Alife script 2 done

**Comment by TodePond** [comment]
Fractal script done, with some improv bits left in

**Comment by TodePond** [comment]
All script done! And I did fractal 2 properly :)

**Comment by TodePond** [comment]
Next up let's do all the transitions

**Comment by TodePond** [comment]
Transitions!

Writing
- [x] Programming Language
- [x] Cellular Automata
- [x] Life
- [x] Intelligence
- [x] Fractal
- [x] Art
- [x] Define

Cards
- [x] Programming Language
- [x] Cellular Automata
- [x] Life
- [x] Intelligence
- [x] Fractal
- [x] Art
- [x] Define

Edit
- [x] Programming Language
- [x] Cellular Automata
- [x] Life / Intelligence
- [x] Fractal
- [x] Art
- [x] Define


Stars
- [x] Programming Language
- [x] Cellular Automata
- [x] Life / Intelligence
- [x] Fractal
- [x] Art
- [x] Define

**Comment by TodePond** [comment]
All cards done

**Comment by TodePond** [comment]
Voice time!

**Comment by TodePond** [comment]
Life voice 1 done

**Comment by TodePond** [comment]
Fractal 1 voice done

**Comment by TodePond** [comment]
All voice 1 done!

**Comment by TodePond** [comment]
Music done!

**Comment by TodePond** [comment]
Notes:

- [x] relax Art timing
- [x] fix cloud precision error again
- [x] double up more speech in life / intelligence
- [x] remove lowpass at start of life / intelligence

**Comment by TodePond** [comment]
Voice 2 time!

**Comment by TodePond** [comment]
Life / Intelligence voice 2 done

**Comment by TodePond** [comment]
Fractal voice 2 done

**Comment by TodePond** [comment]
Reorganised ending so no longer need Define 2 voice

mainly cos i was able to do the collage thing in fractal already, so we get to do something different in define, which is good

**Comment by TodePond** [comment]
Ok I recorded an outro voice instead

**Comment by TodePond** [comment]
Voice 2 all done!!!

**Comment by TodePond** [comment]
Ticking off all the individual transition breakdown because I think I can just go through from start to finish now!

**Comment by Magnogen** [comment]
Oooo we're getting close!

**Comment by TodePond** [comment]
yes! I'll finish it on Wednesday I think!

**Comment by NoenD455** [comment]
yay

**Comment by NoenD455** [comment]
life life or voice life 🤔

**Comment by TodePond** [comment]
Notes:

- [x] Push silence a bit longer at start of art to break the rhythm fully
- [x] Slight audio pop in Life 2

but dang it's looking good

**Comment by NoenD455** [comment]
oh no you didnt finish it on start of Wednesday

**Comment by NoenD455** [comment]
![Screenshot_20230115-181142](https://user-images.githubusercontent.com/107866288/217068956-2f37d26d-c1f9-4fcf-ac99-43502136baff.jpg)
hexagonal wireworld buffers

**Comment by NoenD455** [comment]
fractal life 😱

**Comment by NoenD455** [comment]
add oecake or phyzios studio to third part of tourism

**Comment by NoenD455** [comment]
multiplayer tetris?

**Comment by TodePond** [comment]
More notes 
- [x] try fixing opensea again
- [x] check voice levels, maybe deesser? essssssses very loud

**Comment by TodePond** [comment]
Gonna do Art 1 first just in case I need to do more filming

**Comment by TodePond** [comment]
Art 1 nearly done.
lets work from the start again now

**Comment by TodePond** [comment]
Art 1 done

**Comment by TodePond** [comment]
CA 2 done

**Comment by TodePond** [comment]
Life 1 done

**Comment by TodePond** [comment]
Life 2 done

**Comment by TodePond** [comment]
Fractal 1 done

**Comment by TodePond** [comment]
Fractal 2 done

**Comment by TodePond** [comment]
Art 2 done

**Comment by TodePond** [comment]
all video done! it's rendering.

There's probably some issues with it, so let's see how it goes

**Comment by NoenD455** [comment]
how long is this render?

**Comment by TodePond** [comment]
There was an audio issue in the render so I'll fix it Thursday evening

**Comment by TodePond** [comment]
It's out! 
https://youtu.be/ZMklf0vUl18

**Comment by TodePond** [comment]
Got some reviews ready for promotional toots

**Comment by TodePond** [comment]
I've made some little trailers.

Gonna also write the first "Ribbit Report"
Will do it on train/bus this week

**Comment by TodePond** [comment]
still writing the ribbit report btw the new issue is here: https://github.com/TodePond/Arroost/issues/3

**Comment by i-rember** [comment]
32nd January lol
